language: python
python:
  - "2.7"


install:
  - pip install pytest-cov
  - pip install coveralls
  - pip install flask
  - pip install flask_restful



before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - pytest
  - coverage run --source=app -m pytest && coverage report

after_script:
  - coveralls
  
  
